# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_radioButton.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(839, 660)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblUlke = QtWidgets.QLabel(self.centralwidget)
        self.lblUlke.setGeometry(QtCore.QRect(50, 270, 241, 101))
        self.lblUlke.setText("")
        self.lblUlke.setObjectName("lblUlke")
        self.btnUlkeSecimi = QtWidgets.QPushButton(self.centralwidget)
        self.btnUlkeSecimi.setGeometry(QtCore.QRect(50, 200, 131, 61))
        self.btnUlkeSecimi.setObjectName("btnUlkeSecimi")
        self.btnEgitimSecimi = QtWidgets.QPushButton(self.centralwidget)
        self.btnEgitimSecimi.setGeometry(QtCore.QRect(290, 200, 141, 61))
        self.btnEgitimSecimi.setObjectName("btnEgitimSecimi")
        self.lblEgitim = QtWidgets.QLabel(self.centralwidget)
        self.lblEgitim.setGeometry(QtCore.QRect(290, 270, 251, 101))
        self.lblEgitim.setText("")
        self.lblEgitim.setObjectName("lblEgitim")
        self.groupBoxUlke = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxUlke.setGeometry(QtCore.QRect(30, 10, 221, 191))
        self.groupBoxUlke.setObjectName("groupBoxUlke")
        self.widget = QtWidgets.QWidget(self.groupBoxUlke)
        self.widget.setGeometry(QtCore.QRect(20, 30, 131, 141))
        self.widget.setObjectName("widget")
        self.layoutUlke = QtWidgets.QGridLayout(self.widget)
        self.layoutUlke.setContentsMargins(0, 0, 0, 0)
        self.layoutUlke.setObjectName("layoutUlke")
        self.radioAzerbaycan = QtWidgets.QRadioButton(self.widget)
        self.radioAzerbaycan.setObjectName("radioAzerbaycan")
        self.layoutUlke.addWidget(self.radioAzerbaycan, 3, 0, 1, 1)
        self.radioAlmanya = QtWidgets.QRadioButton(self.widget)
        self.radioAlmanya.setObjectName("radioAlmanya")
        self.layoutUlke.addWidget(self.radioAlmanya, 2, 0, 1, 1)
        self.radioTurkiye = QtWidgets.QRadioButton(self.widget)
        self.radioTurkiye.setObjectName("radioTurkiye")
        self.layoutUlke.addWidget(self.radioTurkiye, 0, 0, 1, 1)
        self.radioYunanistan = QtWidgets.QRadioButton(self.widget)
        self.radioYunanistan.setObjectName("radioYunanistan")
        self.layoutUlke.addWidget(self.radioYunanistan, 4, 0, 1, 1)
        self.groupBoxEgitim = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxEgitim.setGeometry(QtCore.QRect(280, 10, 211, 191))
        self.groupBoxEgitim.setObjectName("groupBoxEgitim")
        self.layoutWidget = QtWidgets.QWidget(self.groupBoxEgitim)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 141, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.layoutEgitim = QtWidgets.QGridLayout(self.layoutWidget)
        self.layoutEgitim.setContentsMargins(0, 0, 0, 0)
        self.layoutEgitim.setObjectName("layoutEgitim")
        self.radioLise = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioLise.setObjectName("radioLise")
        self.layoutEgitim.addWidget(self.radioLise, 1, 0, 1, 1)
        self.radioIlkokul = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioIlkokul.setObjectName("radioIlkokul")
        self.layoutEgitim.addWidget(self.radioIlkokul, 0, 0, 1, 1)
        self.radioUniversite = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioUniversite.setObjectName("radioUniversite")
        self.layoutEgitim.addWidget(self.radioUniversite, 2, 0, 1, 1)
        self.radioYuksekLisans = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioYuksekLisans.setObjectName("radioYuksekLisans")
        self.layoutEgitim.addWidget(self.radioYuksekLisans, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 839, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnUlkeSecimi.setText(_translate("MainWindow", "Ülke Seçimi"))
        self.btnEgitimSecimi.setText(_translate("MainWindow", "Eğitim Seçimi"))
        self.groupBoxUlke.setTitle(_translate("MainWindow", "GroupBox"))
        self.radioAzerbaycan.setText(_translate("MainWindow", "Azerbaycan"))
        self.radioAlmanya.setText(_translate("MainWindow", "Almanya"))
        self.radioTurkiye.setText(_translate("MainWindow", "Türkiye"))
        self.radioYunanistan.setText(_translate("MainWindow", "Yunanistan"))
        self.groupBoxEgitim.setTitle(_translate("MainWindow", "GroupBox"))
        self.radioLise.setText(_translate("MainWindow", "Lise"))
        self.radioIlkokul.setText(_translate("MainWindow", "İlkokul"))
        self.radioUniversite.setText(_translate("MainWindow", "Üniversite"))
        self.radioYuksekLisans.setText(_translate("MainWindow", "Yüksek Lisans"))
